### ISSUE TITLE
eu_cookie admin languages error

### ISSUE THREAD

**Issue by kreossino** [oxigeno2/eu_cookies#1]
hi,
in admin_ui the languages not charged.
i have added in 
..e107_plugins/eu_cookies/admin:config.php
this row.

e107::lan('eu_cookies',true,true);

could you test? thanks

**Comment by kreossino** [comment]
`require_once('../../class2.php');

if (!getperms('P')) 
{
        header('location:'.e_BASE.'index.php');
        exit;
}


//e107::lan('eu_cookies',false,'front'); 
e107::lan('eu_cookies',true,true);

class eu_cookies_adminArea extends e_admin_dispatcher
`

**Comment by oxigeno2** [comment]
Hi, yes fix.
There are more things to fine-tune.
Thanks for the alert!
